version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vector-db-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vector_user -d vector_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  vector-db-svc:
    depends_on:
      postgres:
        condition: service_healthy
    build: 
      context: ./vector-db-svc
      dockerfile: Dockerfile
    container_name: vector-db-svc
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./vector-db-svc:/app
    working_dir: /app

volumes:
  postgres_data:
    driver: local