version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vector-db-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vector_user -d vector_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@stack-ai.com
      PGADMIN_DEFAULT_PASSWORD: myexam123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  vector-db-svc:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    container_name: vector-db-svc
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
  pgadmin-data:
    driver: local